/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.HospitalAdminRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import static Business.Enterprise.Enterprise.EnterpriseType.Distributor;
import Business.Network.Network;
import Business.Organization.HospitalOrganization;
import Business.Organization.Organization;
import Business.Payment.Payment;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.CallBackVaccine;
import Business.WorkQueue.Order;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.FlowLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userinterface.SystemAdminWorkArea.SystemAdminWorkAreaJPanel;

/**
 *
 * @author dharm
 */
public class CallBackHistoryJPanel extends javax.swing.JPanel {

    /**
     * Creates new form VaccineHistoryJPanel
     */
     private JPanel userProcessContainer;
    private EcoSystem business;
    private HospitalOrganization hosOrganization;
   private Order selectedWorkrequest;
   private Network network;
    public CallBackHistoryJPanel(JPanel userProcessContainer,Network network, UserAccount account, HospitalOrganization organization, EcoSystem business) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.business=business;
        this.hosOrganization=organization;
        this.network=network;
        
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        requesttable = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 255, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        requesttable.setFont(new java.awt.Font("Product Sans", 0, 18)); // NOI18N
        requesttable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Quantity", "Cost", "Status", "Message"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        requesttable.setRowHeight(24);
        jScrollPane1.setViewportView(requesttable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 700, 270));

        jButton2.setBackground(new java.awt.Color(0, 51, 51));
        jButton2.setFont(new java.awt.Font("Product Sans", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(153, 255, 153));
        jButton2.setText("Pay Now");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 500, 290, 70));

        jLabel8.setFont(new java.awt.Font("Product Sans", 1, 24)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_back_arrow_50px.png"))); // NOI18N
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 70, 50));

        jLabel9.setFont(new java.awt.Font("Product Sans", 1, 24)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Vaccine History");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 312, -1));

        jLabel10.setFont(new java.awt.Font("Product Sans", 1, 24)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_activity_history_50px.png"))); // NOI18N
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 60, 70, 50));
    }// </editor-fold>//GEN-END:initComponents
    void populateTable(){
         DefaultTableModel model = (DefaultTableModel) requesttable.getModel();

        model.setRowCount(0);
        for (WorkRequest w : hosOrganization.getWorkQueue().getWorkRequestList()) {
            if(w instanceof CallBackVaccine){
            Object[] row = new Object[5];
            row[0] = w;
            row[1] = w.getQuantity();
            row[2] = w.getQuantity()*w.getVaccine().getCost();
            row[3] = w;
            row[4] = w.getMessage();
            
            model.addRow(row);
            }
        }
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
           int selectedRow = requesttable.getSelectedRow();
        CallBackVaccine w=(CallBackVaccine)requesttable.getValueAt(selectedRow, 5);
        w.setStatus("Ready for pick up");
            String str1 = JOptionPane.showInputDialog(null, "Your order is placed.Do you want to add addtional message");
        w.setMessage(str1);
        if(selectedRow >= 0){
             for(Enterprise e : network.getEnterpriseDirectory().getEnterpriseList()) {
               System.out.println("AAAA"+e);
               if(e.getEnterpriseType().equals(Distributor)) {
                    System.out.println("AAAA1"+e);
                    for(Organization o : e.getOrganizationDirectory().getOrganizationList()) {
                        System.out.println("A11111AAA1"+o);
                        if(o.toString().equals("Delivery Organization")){
                            System.out.println("Adding it in provider organization"+o);
                            o.getWorkQueue().addCreatedWorkrequest(w);
                            JOptionPane.showMessageDialog(null, "Order was placed successfully!");
                        } else {
                            //JOptionPane.showMessageDialog(null, "Order could not be placed.");
                        }
                    }
                } 
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageHospitalJPanle sysAdminwjp = (ManageHospitalJPanle) component;
        sysAdminwjp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jLabel8MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable requesttable;
    // End of variables declaration//GEN-END:variables
}
