/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.HospitalAdminRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import static Business.Enterprise.Enterprise.EnterpriseType.Distributor;
import Business.Network.Network;
import Business.Organization.HospitalOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.Vaccine.Vaccine;
import Business.WorkQueue.Order;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userinterface.CDCAdmin.ManageVaccine;
import userinterface.InventoryManagerRole.ManageVaccineOrdersJPanel;
import userinterface.SystemAdminWorkArea.ManageEnterpriseAdminJPanel;

/**
 *
 * @author dharm
 */
public class ManageHospitalJPanle extends javax.swing.JPanel {

    /**
     * Creates new form ManageHospitalJPanle
     */
    private JPanel userProcessContainer;
    private EcoSystem business;
    private UserAccount userAccount;
    private HospitalOrganization hosOrganization;
    private Network network;

    public ManageHospitalJPanle(JPanel userProcessContainer,Network network, UserAccount account, Organization organization, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.business = business;
        this.hosOrganization = (HospitalOrganization)organization;
        this.network=network;
        populateTable();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        VaccineTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        quantity = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 255, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        VaccineTable.setFont(new java.awt.Font("Product Sans", 0, 18)); // NOI18N
        VaccineTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Cost"
            }
        ));
        VaccineTable.setRowHeight(24);
        jScrollPane1.setViewportView(VaccineTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 640, 210));

        jButton1.setFont(new java.awt.Font("Product Sans", 0, 18)); // NOI18N
        jButton1.setText("Place Order");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 470, 210, 50));

        jButton2.setFont(new java.awt.Font("Product Sans", 0, 18)); // NOI18N
        jButton2.setText("VIew Order History");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 530, 210, 50));

        jLabel2.setFont(new java.awt.Font("Product Sans", 0, 18)); // NOI18N
        jLabel2.setText("Quantity");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 420, -1, 30));

        quantity.setFont(new java.awt.Font("Product Sans", 0, 18)); // NOI18N
        add(quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 420, 130, 30));

        jLabel8.setFont(new java.awt.Font("Product Sans", 1, 24)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Hospital Dashboard");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 312, -1));
    }// </editor-fold>//GEN-END:initComponents
     void populateTable(){
         DefaultTableModel model = (DefaultTableModel) VaccineTable.getModel();

        model.setRowCount(0);
        for (Vaccine v : business.getVaccinedir().getVaccDir()) {
                    Object[] row = new Object[3];
                    row[0] = v;
                    row[1] = v.getCost();
                    row[2] = v.getDesc();
                    model.addRow(row);
         }
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int selectedRow = VaccineTable.getSelectedRow();
        if(selectedRow >= 0){
            String str1 = JOptionPane.showInputDialog(null, "Your order is placed.Do you want to add addtional message");
       
            Vaccine v = (Vaccine)VaccineTable.getValueAt(selectedRow, 0);
            Order w = hosOrganization.getWorkQueue().addWorkRequestList();
            w.setSender(userAccount);
            w.setStatus("Order placed");
            w.setMessage(str1);
            w.setVaccine(v);
            w.setHos(hosOrganization);
            w.setQuantity(Integer.parseInt(quantity.getText()));
            w.setNetwork(network.getName());
           
            for(Enterprise e : network.getEnterpriseDirectory().getEnterpriseList()) {
               System.out.println("AAAA"+e);
               if(e.getEnterpriseType().equals(Distributor)) {
                    System.out.println("AAAA1"+e);
                    for(Organization o : e.getOrganizationDirectory().getOrganizationList()) {
                        System.out.println("A11111AAA1"+o);
                        if(o.toString().equals("Provider Organization")){
                            System.out.println("Adding it in provider organization"+o);
                            o.getWorkQueue().addCreatedWorkrequest(w);
                            JOptionPane.showMessageDialog(null, "Order was placed successfully!");
                        } else {
                            //JOptionPane.showMessageDialog(null, "Order could not be placed.");
                        }
                    }
                } 
            }
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
            VaccineHistoryJPanel manageEnterpriseAdminJPanel=new VaccineHistoryJPanel(userProcessContainer,business,hosOrganization);
            userProcessContainer.add("manageEnterpriseAdminJPanel",manageEnterpriseAdminJPanel);
            CardLayout layout=(CardLayout)userProcessContainer.getLayout();
            layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable VaccineTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField quantity;
    // End of variables declaration//GEN-END:variables
}
