/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Role.AdminRole;
import Business.Role.CDCAdminRole;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.RegisterVaccine;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author raunak
 */
public class ManageCDCAdminJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem system;

    /**
     * Creates new form ManageEnterpriseJPanel
     */
    public ManageCDCAdminJPanel(JPanel userProcessContainer, EcoSystem system) {
        initComponents();

        this.userProcessContainer = userProcessContainer;
        this.system = system;
        populateTable();
        //populateNetworkComboBox();
    }

     

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        usernameJTextField = new javax.swing.JTextField();
        submitJButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        nameJTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        passwordJPasswordField = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        phoneTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        locationTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        CdcTable = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 255, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Product Sans", 1, 18)); // NOI18N
        jLabel2.setText("Username");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, -1, -1));

        usernameJTextField.setFont(new java.awt.Font("Product Sans", 0, 18)); // NOI18N
        add(usernameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 440, 190, -1));

        submitJButton.setBackground(new java.awt.Color(0, 51, 51));
        submitJButton.setFont(new java.awt.Font("Product Sans", 1, 24)); // NOI18N
        submitJButton.setForeground(new java.awt.Color(102, 255, 102));
        submitJButton.setText("Submit");
        submitJButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });
        add(submitJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 620, 300, 50));

        jLabel4.setFont(new java.awt.Font("Product Sans", 1, 18)); // NOI18N
        jLabel4.setText("Password");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 490, -1, -1));

        nameJTextField.setFont(new java.awt.Font("Product Sans", 0, 18)); // NOI18N
        add(nameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 540, 190, -1));

        jLabel5.setFont(new java.awt.Font("Product Sans", 1, 18)); // NOI18N
        jLabel5.setText("Name");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 540, -1, 30));

        passwordJPasswordField.setFont(new java.awt.Font("Product Sans", 0, 18)); // NOI18N
        add(passwordJPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 490, 190, -1));

        jLabel1.setFont(new java.awt.Font("Product Sans", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_back_arrow_50px.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 70, 60));
        jLabel1.getAccessibleContext().setAccessibleDescription("");

        jLabel3.setFont(new java.awt.Font("Product Sans", 1, 18)); // NOI18N
        jLabel3.setText("Email Id");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 440, -1, 30));

        jLabel7.setFont(new java.awt.Font("Product Sans", 1, 18)); // NOI18N
        jLabel7.setText("Phone Number");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 490, -1, -1));

        emailTextField.setFont(new java.awt.Font("Product Sans", 0, 18)); // NOI18N
        add(emailTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 440, 190, -1));

        phoneTextField.setFont(new java.awt.Font("Product Sans", 0, 18)); // NOI18N
        add(phoneTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 490, 190, -1));

        jLabel8.setFont(new java.awt.Font("Product Sans", 1, 18)); // NOI18N
        jLabel8.setText("Location");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 540, -1, -1));

        locationTextField.setFont(new java.awt.Font("Product Sans", 0, 18)); // NOI18N
        add(locationTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 540, 190, -1));

        CdcTable.setFont(new java.awt.Font("Product Sans", 0, 18)); // NOI18N
        CdcTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "UserName", "Email", "Contact Number"
            }
        ));
        CdcTable.setRowHeight(24);
        jScrollPane1.setViewportView(CdcTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 720, 260));

        jLabel6.setFont(new java.awt.Font("Product Sans", 1, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Manage CDC Admin");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 240, -1));

        jLabel9.setFont(new java.awt.Font("Product Sans", 1, 24)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_administrator_male_50px.png"))); // NOI18N
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 40, 70, 60));
    }// </editor-fold>//GEN-END:initComponents
    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed
        
        
        String username = usernameJTextField.getText();
        String password = String.valueOf(passwordJPasswordField.getPassword());
        String name = nameJTextField.getText();
        String emailId = emailTextField.getText();
        String phoneNumber = phoneTextField.getText();
        String location = locationTextField.getText();
        Employee employee = system.getCdcOrganization().getEmployeeDirectory().createEmployee(name, emailId, phoneNumber, location);
        //Creating User
       // User user = system.getCdcOrganization().getUserDir().createUser(name, emailId, phoneNumber);
        UserAccount account = system.getCdcOrganization().getUserAccountDirectory().createUserAccount(username, password, employee, new CDCAdminRole());
        JOptionPane.showMessageDialog(null, "Account created Successfully");
    }//GEN-LAST:event_submitJButtonActionPerformed
    void populateTable(){
        DefaultTableModel model = (DefaultTableModel) CdcTable.getModel();

        model.setRowCount(0);
        try{
        for(UserAccount w :system.getCdcOrganization().getUserAccountDirectory().getUserAccountList()) {
            Object[] row = new Object[4];
            row[0] = w.getEmployee();
            row[1] = w.getUsername();
            row[2] = w.getEmployee().getEmailId();
            row[3] = w.getEmployee().getPhoneNumber();
            model.addRow(row);
            }
        }catch(Exception e){
            System.out.println("No CDC");
        }
    }
    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        SystemAdminWorkAreaJPanel sysAdminwjp = (SystemAdminWorkAreaJPanel) component;
        sysAdminwjp.populateTree();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jLabel1MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable CdcTable;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField locationTextField;
    private javax.swing.JTextField nameJTextField;
    private javax.swing.JPasswordField passwordJPasswordField;
    private javax.swing.JTextField phoneTextField;
    private javax.swing.JButton submitJButton;
    private javax.swing.JTextField usernameJTextField;
    // End of variables declaration//GEN-END:variables
}
