/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterfacePackage;

import Business.User.UserDirectory;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author imskr
 */
public class DeliveryManagerWorkArea extends javax.swing.JPanel {
    
    private JPanel viewJPanel;
    private UserDirectory directory;

    /**
     * Creates new form DeliveryManagerWorkArea
     */
    DeliveryManagerWorkArea(JPanel viewJPanel, UserDirectory directory, String text) {
        initComponents();
        this.viewJPanel = viewJPanel;
        this.directory = directory;
        jLabel48.setText(text);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel12 = new keeptoo.KGradientPanel();
        jLabel45 = new javax.swing.JLabel();
        button_AddDeliveryPerson11 = new keeptoo.KButton();
        button_manageDeliveryPerson11 = new keeptoo.KButton();
        button_viewDeliveries11 = new keeptoo.KButton();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel45.setFont(new java.awt.Font("Product Sans", 1, 36)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setText("Delivery Manager Work Area");

        button_AddDeliveryPerson11.setText("Add Delivery Person");
        button_AddDeliveryPerson11.setFont(new java.awt.Font("Product Sans", 1, 18)); // NOI18N
        button_AddDeliveryPerson11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_AddDeliveryPersonActionPerformed(evt);
            }
        });

        button_manageDeliveryPerson11.setText("Manage Delivery Person");
        button_manageDeliveryPerson11.setFont(new java.awt.Font("Product Sans", 1, 18)); // NOI18N
        button_manageDeliveryPerson11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_manageDeliveryPersonActionPerformed(evt);
            }
        });

        button_viewDeliveries11.setText("View Deliveries");
        button_viewDeliveries11.setFont(new java.awt.Font("Product Sans", 1, 18)); // NOI18N
        button_viewDeliveries11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_viewDeliveries11ActionPerformed(evt);
            }
        });

        jLabel46.setFont(new java.awt.Font("Product Sans", 1, 36)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setText("Hi, ");

        jLabel47.setFont(new java.awt.Font("Product Sans", 1, 36)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 255, 255));

        jLabel48.setFont(new java.awt.Font("Product Sans", 1, 36)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout kGradientPanel12Layout = new javax.swing.GroupLayout(kGradientPanel12);
        kGradientPanel12.setLayout(kGradientPanel12Layout);
        kGradientPanel12Layout.setHorizontalGroup(
            kGradientPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel12Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(kGradientPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel12Layout.createSequentialGroup()
                        .addGroup(kGradientPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(kGradientPanel12Layout.createSequentialGroup()
                                .addComponent(jLabel46)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel48, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel45, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel47))
                    .addGroup(kGradientPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(button_viewDeliveries11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(button_manageDeliveryPerson11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(button_AddDeliveryPerson11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)))
                .addContainerGap(265, Short.MAX_VALUE))
        );
        kGradientPanel12Layout.setVerticalGroup(
            kGradientPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel12Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(kGradientPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(button_AddDeliveryPerson11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(button_manageDeliveryPerson11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(button_viewDeliveries11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(313, Short.MAX_VALUE))
        );

        add(kGradientPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 735));
    }// </editor-fold>//GEN-END:initComponents

    private void button_manageDeliveryPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_manageDeliveryPersonActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout)viewJPanel.getLayout();
        viewJPanel.add(new ManageDeliveryPersonJPanel(viewJPanel, directory));
        layout.next(viewJPanel);
    }//GEN-LAST:event_button_manageDeliveryPersonActionPerformed

    private void button_AddDeliveryPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_AddDeliveryPersonActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout)viewJPanel.getLayout();
        viewJPanel.add(new CreateDeliveryPersonJPanel(viewJPanel, directory));
        layout.next(viewJPanel);
    }//GEN-LAST:event_button_AddDeliveryPersonActionPerformed

    private void button_viewDeliveries11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_viewDeliveries11ActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout)viewJPanel.getLayout();
        viewJPanel.add(new ViewDeliveryPerson(viewJPanel, directory));
        layout.next(viewJPanel);
    }//GEN-LAST:event_button_viewDeliveries11ActionPerformed

  
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KButton button_AddDeliveryPerson11;
    private keeptoo.KButton button_manageDeliveryPerson11;
    private keeptoo.KButton button_viewDeliveries11;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private keeptoo.KGradientPanel kGradientPanel12;
    // End of variables declaration//GEN-END:variables
}
