/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterfacePackage;

import Business.User.User;
import Business.User.UserDirectory;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author imskr
 */
public class ModifyDeliveryPersonJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ModifyDeliveryPersonJPanel
     */
    
    private JPanel viewJPanel;
    private UserDirectory directory;
    private User user;

    ModifyDeliveryPersonJPanel(JPanel viewJPanel, User user, UserDirectory directory) {
        initComponents();
        this.viewJPanel = viewJPanel;
        this.directory = directory;
        this.user = user;
        displaySelectedUser();
    }
    
    private void displaySelectedUser() {
        txt_name.setText(user.getName());
        txt_username.setText(user.getUserName());
        txt_password.setText(user.getPassword());
        txt_address.setText(user.getAddress());
        txt_phoneNumber.setText(user.getPhoneNumber());
        
        txt_name.setEnabled(false);
        txt_username.setEnabled(false);
        txt_password.setEnabled(false);
        txt_address.setEnabled(false);
        txt_phoneNumber.setEnabled(false);
        button_save.setEnabled(false);
        button_update.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        txt_username = new javax.swing.JTextField();
        txt_address = new javax.swing.JTextField();
        txt_phoneNumber = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        button_update = new javax.swing.JButton();
        button_save = new javax.swing.JButton();
        button_back = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txt_password = new javax.swing.JTextField();

        jLabel1.setText("Name: ");

        jLabel2.setText("Username: ");

        jLabel3.setText("Address: ");

        jLabel4.setText("Phone Number: ");

        jLabel5.setText("VIEW DELIVERY PERSON");

        button_update.setText("Update");
        button_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_updateActionPerformed(evt);
            }
        });

        button_save.setText("Save");
        button_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_saveActionPerformed(evt);
            }
        });

        button_back.setText("<< Back");
        button_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_backActionPerformed(evt);
            }
        });

        jLabel6.setText("Password: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(button_back)
                .addGap(103, 103, 103)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_address)
                            .addComponent(txt_phoneNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(button_update)
                        .addGap(18, 18, 18)
                        .addComponent(button_save))
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(jLabel1))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_name)
                            .addComponent(txt_username)
                            .addComponent(txt_password, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE))))
                .addContainerGap(320, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(button_back))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_phoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_update)
                    .addComponent(button_save))
                .addContainerGap(221, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void toMainScreen() {
        CardLayout layout = (CardLayout)this.viewJPanel.getLayout();
        this.viewJPanel.remove(this);
        Component[] comps = this.viewJPanel.getComponents();
        for(Component comp : comps)
        {
            if(comp instanceof ViewDeliveryPerson)
            {
                ViewDeliveryPerson panel=(ViewDeliveryPerson)comp;
                panel.populateTable();
            }
        }
    }
    
    private void button_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_backActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout)viewJPanel.getLayout();
        viewJPanel.remove(this);
        layout.previous(viewJPanel);
        toMainScreen();
    }//GEN-LAST:event_button_backActionPerformed

    private void button_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_updateActionPerformed
        // TODO add your handling code here:
        button_update.setEnabled(false);
        button_save.setEnabled(true);
        txt_name.setEnabled(true);
        txt_username.setEnabled(true);
        txt_password.setEnabled(true);
        txt_address.setEnabled(true);
        txt_phoneNumber.setEnabled(true);
    }//GEN-LAST:event_button_updateActionPerformed

    private void button_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_saveActionPerformed
        // TODO add your handling code here:
        String newName = txt_name.getText();
        String newUsername = txt_username.getText();
        String newPassword = txt_password.getText();
        String newAddress = txt_address.getText();
        String newPhone = txt_phoneNumber.getText();
        if (this.directory.updateUser(new User(newName, newUsername, newPassword, 
                newAddress, newPhone), user)) {
            JOptionPane.showMessageDialog(null, "Updation performed successfully!");
            
        } else {
            JOptionPane.showMessageDialog(null, "Updation failed!");
        }

        button_update.setEnabled(true);
        button_save.setEnabled(false);
    }//GEN-LAST:event_button_saveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_back;
    private javax.swing.JButton button_save;
    private javax.swing.JButton button_update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txt_address;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_password;
    private javax.swing.JTextField txt_phoneNumber;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
