/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterfacePackage;

import Business.User.UserDirectory;
import Business.WorkRequest.WorkQueue;
import Business.WorkRequest.WorkRequest;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author imskr
 */
public class ProviderWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form ProviderWorkArea
     */
    
    private JPanel viewJPanel;
    private UserDirectory directory;
    private WorkQueue wq;

    ProviderWorkArea(JPanel viewJPanel, UserDirectory directory, String text, WorkQueue wq) {
        initComponents();
        this.viewJPanel = viewJPanel;
        this.directory = directory;
        this.wq = wq;
        populateTable();
    }
    
    public void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) table_provider.getModel();
        dtm.setRowCount(0);
        Object[] row = new Object[3];
         for (WorkRequest wr : wq.getWorkRequestList()) {
            row[0] = wr.getVaccine();
            row[1] = wr.getHospital();
            row[2] = wr.getStatus();
            dtm.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        providerWorkAreaJPanel = new keeptoo.KGradientPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_provider = new javax.swing.JTable();
        button_process = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        table_provider.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Vaccine Requested", "Hospital", "Status"
            }
        ));
        jScrollPane1.setViewportView(table_provider);

        button_process.setText("Process Request");

        jLabel1.setFont(new java.awt.Font("Product Sans", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PROVIDER WORK AREA");

        javax.swing.GroupLayout providerWorkAreaJPanelLayout = new javax.swing.GroupLayout(providerWorkAreaJPanel);
        providerWorkAreaJPanel.setLayout(providerWorkAreaJPanelLayout);
        providerWorkAreaJPanelLayout.setHorizontalGroup(
            providerWorkAreaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(providerWorkAreaJPanelLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(providerWorkAreaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(button_process, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 726, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        providerWorkAreaJPanelLayout.setVerticalGroup(
            providerWorkAreaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(providerWorkAreaJPanelLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(button_process, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(168, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(providerWorkAreaJPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 862, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(providerWorkAreaJPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_process;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private keeptoo.KGradientPanel providerWorkAreaJPanel;
    private javax.swing.JTable table_provider;
    // End of variables declaration//GEN-END:variables
}
