/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterfacePackage;

import Business.User.User;
import Business.User.UserDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author imskr
 */
public class ViewDeliveryPerson extends javax.swing.JPanel {

    /**
     * Creates new form ViewDeliveryPerson
     */
    
    private JPanel viewJPanel;
    private UserDirectory directory;

    ViewDeliveryPerson(JPanel viewJPanel, UserDirectory directory) {
        initComponents();
        this.viewJPanel = viewJPanel;
        this.directory = directory;
        populateTable();
    }
    
    public void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel)table_deliveryPerson.getModel();
        dtm.setRowCount(0);
        Object[] row = new Object[5];
        for (User u : directory.getDirectory()) {
            row[0] = u;
            row[1] = u.getUserName();
            row[2] = u.getPassword();
            row[3] = u.getAddress();
            row[4] = u.getPhoneNumber();
            dtm.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table_deliveryPerson = new javax.swing.JTable();
        button_view = new javax.swing.JButton();
        button_delete = new javax.swing.JButton();
        button_goBack = new javax.swing.JButton();

        table_deliveryPerson.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Username", "Password", "Address", "Phone Number"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table_deliveryPerson);
        if (table_deliveryPerson.getColumnModel().getColumnCount() > 0) {
            table_deliveryPerson.getColumnModel().getColumn(0).setResizable(false);
            table_deliveryPerson.getColumnModel().getColumn(1).setResizable(false);
            table_deliveryPerson.getColumnModel().getColumn(2).setResizable(false);
            table_deliveryPerson.getColumnModel().getColumn(3).setResizable(false);
            table_deliveryPerson.getColumnModel().getColumn(4).setResizable(false);
        }

        button_view.setText("View");
        button_view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_viewActionPerformed(evt);
            }
        });

        button_delete.setText("Delete");

        button_goBack.setText("Go Back");
        button_goBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_goBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(button_view, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(button_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(button_goBack, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_view, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_goBack, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(201, 201, 201))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void button_viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_viewActionPerformed
        // TODO add your handling code here:
        int selectedRow = table_deliveryPerson.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select row to view details.");
        } else {
            User user = (User) table_deliveryPerson.getValueAt(selectedRow, 0);
            CardLayout layout = (CardLayout)viewJPanel.getLayout();
            viewJPanel.add(new ModifyDeliveryPersonJPanel(viewJPanel, user, directory));
            layout.next(viewJPanel);
        }
        
    }//GEN-LAST:event_button_viewActionPerformed

    private void button_goBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_goBackActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout)viewJPanel.getLayout();
        viewJPanel.remove(this);
        layout.previous(viewJPanel);
    }//GEN-LAST:event_button_goBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_delete;
    private javax.swing.JButton button_goBack;
    private javax.swing.JButton button_view;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_deliveryPerson;
    // End of variables declaration//GEN-END:variables
}
