/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.ProviderRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import static Business.Enterprise.Enterprise.EnterpriseType.Distributor;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Organization.ProviderOrganization;
import Business.UserAccount.UserAccount;
import Business.Vaccine.Vaccine;
import Business.WorkQueue.Order;
import Business.WorkQueue.WorkRequest;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userinterface.PHDLead.PHDLeadWorkAreaJPanel;

/**
 *
 * @author imskr
 */
public final class ProviderWorkAreaJPanel extends javax.swing.JPanel {
    
    private final JPanel userProcessContainer;
    private final ProviderOrganization organization;
    private final Enterprise enterprise;
    private final UserAccount userAccount;
    private Network network;
    private EcoSystem business;
    
    /**
     * Creates new form ProviderWorkAreaJPanel
     * @param userProcessContainer
     * @param account
     * @param organization
     * @param enterprise
     */
    public ProviderWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, ProviderOrganization organization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.network = network;
        this.business = business;
        valueLabel.setText(enterprise.getName());
        populateRequestTable();
    }
    
    public void populateRequestTable(){
        DefaultTableModel model = (DefaultTableModel) workRequestJTable.getModel();
        model.setRowCount(0);
        for (WorkRequest request : organization.getWorkQueue().getWorkRequestList()){
            Object[] row = new Object[7];
            row[0] = request.getVaccine().getName();
            row[1] = request.getSender();
            row[2] = request.getQuantity();
            row[3] = request.getQuantity()*request.getVaccine().getCost();
            row[4] = request;
            row[5] = request.getMessage();
            row[6] = request.getRequestDate();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        workRequestJTable = new javax.swing.JTable();
        button_approve = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        workRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Vaccine", "Hospital", "Quantity", "Cost", "Status", "Message", "Created Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(workRequestJTable);
        if (workRequestJTable.getColumnModel().getColumnCount() > 0) {
            workRequestJTable.getColumnModel().getColumn(0).setResizable(false);
            workRequestJTable.getColumnModel().getColumn(2).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 810, 341));

        button_approve.setText("Forward Request");
        button_approve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_approveActionPerformed(evt);
            }
        });
        add(button_approve, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, -1, -1));

        jLabel1.setFont(new java.awt.Font("Product Sans", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Provider Work Area");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 810, -1));

        valueLabel.setFont(new java.awt.Font("Product Sans", 1, 18)); // NOI18N
        valueLabel.setText("<Enterprise Name>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 500, 20));

        jLabel3.setFont(new java.awt.Font("Product Sans", 1, 18)); // NOI18N
        jLabel3.setText("Enterprise Name: ");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void button_approveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_approveActionPerformed
        // TODO add your handling code here:

	//select a row from table
        int selectedRow=workRequestJTable.getSelectedRow();
        if(selectedRow>=0){
            String str1 = JOptionPane.showInputDialog(null, "Your order is placed.Do you want to add addtional message");
       		
		//get workrequest from workRequestJTable..
            WorkRequest w =(WorkRequest)workRequestJTable.getValueAt(selectedRow, 4);
            w.setStatus("Sent to PHD");
            w.setMessage(str1);
            for(Organization o:enterprise.getOrganizationDirectory().getOrganizationList()){
                        if(o.toString().equals("PHD Organization")){
                            System.out.println("YAYYY"+o);
                            o.getWorkQueue().addCreatedWorkrequest(w);
                        } else {
                          //  JOptionPane.showMessageDialog(null, "Order could not be placed.");
                        }
                    
            }
            populateRequestTable();
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row first.");
        }
        
    }//GEN-LAST:event_button_approveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_approve;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel valueLabel;
    private javax.swing.JTable workRequestJTable;
    // End of variables declaration//GEN-END:variables
}
