/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CDCAdmin;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.UserAccount.UserAccount;
import Business.Vaccine.Vaccine;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dharm
 */
public class ManageVaccine extends javax.swing.JPanel {

    /**
     * Creates new form ManageVaccine
     */
    JPanel userProcessContainer;
    EcoSystem ecosystem;
    public ManageVaccine(JPanel userProcessContainer, EcoSystem ecosystem) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.ecosystem = ecosystem;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        VaccineTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        codeField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        DescField = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        batchField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        CostField2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        manufactField = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 255, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        VaccineTable.setFont(new java.awt.Font("Product Sans", 0, 18)); // NOI18N
        VaccineTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Name", "Cost", "Description"
            }
        ));
        VaccineTable.setRowHeight(24);
        jScrollPane1.setViewportView(VaccineTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 560, 170));

        jButton1.setText("Create");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 460, 270, 40));

        jLabel2.setFont(new java.awt.Font("Product Sans", 0, 18)); // NOI18N
        jLabel2.setText("Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 310, 70, -1));

        nameField.setFont(new java.awt.Font("Product Sans", 0, 18)); // NOI18N
        add(nameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, 170, -1));

        jLabel3.setFont(new java.awt.Font("Product Sans", 0, 18)); // NOI18N
        jLabel3.setText("Code");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, 50, 20));

        codeField.setFont(new java.awt.Font("Product Sans", 0, 18)); // NOI18N
        codeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codeFieldActionPerformed(evt);
            }
        });
        add(codeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, 170, -1));

        jLabel4.setFont(new java.awt.Font("Product Sans", 0, 18)); // NOI18N
        jLabel4.setText("Description");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 403, 110, 30));

        DescField.setColumns(20);
        DescField.setRows(5);
        jScrollPane2.setViewportView(DescField);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, 170, 120));

        jButton3.setText("< Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, -1, -1));

        jLabel8.setFont(new java.awt.Font("Product Sans", 1, 24)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Manage Vaccine");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 55, 412, -1));

        jLabel5.setFont(new java.awt.Font("Product Sans", 0, 18)); // NOI18N
        jLabel5.setText("Batch Size");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 310, 100, -1));

        batchField.setFont(new java.awt.Font("Product Sans", 0, 18)); // NOI18N
        batchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batchFieldActionPerformed(evt);
            }
        });
        add(batchField, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 310, 170, -1));

        jLabel6.setFont(new java.awt.Font("Product Sans", 0, 18)); // NOI18N
        jLabel6.setText("Cost");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 350, 40, 20));

        CostField2.setFont(new java.awt.Font("Product Sans", 0, 18)); // NOI18N
        CostField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CostField2ActionPerformed(evt);
            }
        });
        add(CostField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 350, 170, -1));

        jLabel7.setFont(new java.awt.Font("Product Sans", 0, 18)); // NOI18N
        jLabel7.setText("Manufacture:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 390, 110, 20));

        manufactField.setFont(new java.awt.Font("Product Sans", 0, 18)); // NOI18N
        manufactField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manufactFieldActionPerformed(evt);
            }
        });
        add(manufactField, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 390, 170, -1));
    }// </editor-fold>//GEN-END:initComponents
    void populateTable(){
         DefaultTableModel model = (DefaultTableModel) VaccineTable.getModel();

        model.setRowCount(0);
        for (Vaccine v : ecosystem.getVaccinedir().getVaccDir()) {
                    Object[] row = new Object[3];
                    row[0] = v;
                    row[1] = v.getCost();
                    row[2] = v.getDesc();

                    model.addRow(row);
         }
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Vaccine v = ecosystem.getVaccinedir().addVaccDir();
        v.setCost(Float.parseFloat(codeField.getText()));
        v.setDesc(DescField.getText());
        v.setName(nameField.getText());
        v.setCode(codeField.getText());
        v.setManufact(manufactField.getText());
        v.setBatch(Integer.parseInt(batchField.getText()));
        populateTable();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void codeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codeFieldActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void batchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_batchFieldActionPerformed

    private void CostField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CostField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CostField2ActionPerformed

    private void manufactFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manufactFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_manufactFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CostField2;
    private javax.swing.JTextArea DescField;
    private javax.swing.JTable VaccineTable;
    private javax.swing.JTextField batchField;
    private javax.swing.JTextField codeField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField manufactField;
    private javax.swing.JTextField nameField;
    // End of variables declaration//GEN-END:variables
}
